SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [flw].[GetConfigTableColumns]
()
RETURNS TABLE
AS
RETURN
(
    SELECT QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) + '.' + QUOTENAME(COLUMN_NAME) AS ObjectName
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME)IN
          (
              SELECT ObjectName FROM [flw].[GetConfigTables]()
          )
          --AND CHARACTER_MAXIMUM_LENGTH <> -1 --Exclude Varchar Max columns
);
GO
