SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO













CREATE VIEW [flw].[FlowDS]
AS
SELECT ds.FlowID,
       [InvokeType] AS FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       '' AS trgServer,
       COALESCE([PipelineName], [RunbookName], '') AS trgDBSchObj,
       NULL [trgDatabase],
       NULL AS [trgSchema],
       COALESCE([PipelineName], [RunbookName], '') AS [trgObject],
       ISNULL([InvokeType], '') [SourceType],
       COALESCE(trgServicePrincipalAlias, '') [DatabaseName],
       [InvokeAlias] AS [Alias],
       0 [IsSynapse],
       0 [IsLocal],
       NULL [FromObjectMK],
       ds.[ToObjectMK],
       1 DS,
       NULL AS preFilter,
       '--> ' + COALESCE(trgServicePrincipalAlias, '') + '.' + ISNULL([InvokeType], '')
       + COALESCE([PipelineName], [RunbookName], '') AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + '--> ' + COALESCE([PipelineName], [RunbookName], '') AS [ProcessShort],
       DeactivateFromBatch,
       [InvokeAlias] AS [SrcAlias],
       '' AS [TrgAlias],
       '' AS trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[Invoke] ds
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.trgDBSchSP AS trgDBSchObj,
       PARSENAME(ds.trgDBSchSP, 3) AS [trgDatabase],
       PARSENAME(ds.trgDBSchSP, 2) AS [trgSchema],
       PARSENAME(ds.trgDBSchSP, 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       2 DS,
       NULL AS preFilter,
       '--> ' + [trgServer] + '.' + ds.[trgDBSchSP] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + '--> ' + [flw].[GetObjectName](ds.[trgDBSchSP]) AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       '' AS trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM flw.StoredProcedure ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       3 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionXML] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       4 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionXLS] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       5 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionCSV] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
    LEFT OUTER JOIN [flw].[LineageObjectMK] mk
        ON mk.ObjectMK = ds.[ToObjectMK]
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       6 DS,
       preFilter AS preFilter,
       [srcServer] + '.' + [flw].[GetADOSourceName](ds.FlowID) + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [flw].[GetADOSourceName](ds.FlowID) + ' --> '
       + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [Process],
       DeactivateFromBatch,
       [srcServer] AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionADO] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
    LEFT OUTER JOIN [flw].[LineageObjectMK] mk
        ON mk.ObjectMK = ds.[ToObjectMK]
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       ds.trgServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       7 DS,
       NULL AS preFilter,
       ds.[srcServer] + '.' + ds.[srcDBSchTbl] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [flw].[GetObjectName](ds.[srcDBSchTbl]) + ' --> '
       + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       [srcServer] AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       ds.srcDBSchTbl AS srcDBSchObj,
       PARSENAME(ds.srcDBSchTbl, 3) AS [srcDatabase],
       PARSENAME(ds.srcDBSchTbl, 2) AS [srcSchema],
       PARSENAME(ds.srcDBSchTbl, 1) AS [srcObject],
       KeyColumns AS KeyColumns,
       [DateColumn] AS [DateColumn]
FROM [flw].[Ingestion] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.srcServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       ds.srcServer,
       '' AS trgServer,
       ds.[srcDBSchTbl],
       PARSENAME(ds.[srcDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[srcDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[srcDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       8 DS,
       NULL AS preFilter,
       ds.[srcServer] + '.' + ds.[srcDBSchTbl] + ' --> ' + [trgPath] + '.' + [trgFileName] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [flw].[GetObjectName](ds.[srcDBSchTbl]) + ' --> ' + [trgPath]
       + '.' + [trgFileName] AS [ProcessShort],
       DeactivateFromBatch,
       [srcServer] AS [SrcAlias],
       '' AS [TrgAlias],
       '' AS trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[Export] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.srcServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       9 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionJSN] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       '' AS srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       10 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + ds.[trgDBSchTbl] AS [ProcessShort],
       DeactivateFromBatch,
       '' AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionPRQ] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       ds.FlowType,
       ds.SysAlias,
       ds.Batch,
       ds.srcServer,
       ds.trgServer,
       ds.[trgDBSchTbl],
       PARSENAME(ds.[trgDBSchTbl], 3) AS [trgDatabase],
       PARSENAME(ds.[trgDBSchTbl], 2) AS [trgSchema],
       PARSENAME(ds.[trgDBSchTbl], 1) AS [trgObject],
       s.[SourceType],
       s.DatabaseName AS DatabaseName,
       s.[Alias],
       s.[IsSynapse],
       s.[IsLocal],
       ds.[FromObjectMK],
       ds.[ToObjectMK],
       10 DS,
       preFilter AS preFilter,
       [srcPath] + [srcFile] + ' --> ' + [trgServer] + '.' + ds.[trgDBSchTbl] AS [Process],
       '(' + CAST(ds.FlowID AS VARCHAR(50)) + ') ' + [srcFile] + ' --> ' + [flw].[GetObjectName](ds.[trgDBSchTbl]) AS [ProcessShort],
       DeactivateFromBatch,
       [srcServer] AS [SrcAlias],
       [trgServer] AS [TrgAlias],
       trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[PreIngestionPRC] ds
    INNER JOIN [flw].[SysDataSource] s
        ON ds.trgServer = s.Alias
UNION
SELECT ds.FlowID,
       FlowType,
       ds.Batch AS SysAlias,
       ds.Batch,
       '' AS [srcServer],
       '' AS trgServer,
       COALESCE(SubscriberName, '') AS trgDBSchObj,
       NULL [trgDatabase],
       NULL AS [trgSchema],
       COALESCE(SubscriberName, '') AS [trgObject],
       '' [SourceType],
       '' [DatabaseName],
       '' AS [Alias],
       0 [IsSynapse],
       0 [IsLocal],
       NULL [FromObjectMK],
       ds.[ToObjectMK],
       11 DS,
       NULL AS preFilter,
       '-->' + [SubscriberName] AS [Process],
       '-->' + [SubscriberName] AS [ProcessShort],
       CAST(0 AS BIT) AS DeactivateFromBatch,
       '' AS [SrcAlias],
       '' AS [TrgAlias],
       '' AS trgDesiredIndex,
       NULL AS srcDBSchObj,
       NULL AS [srcDatabase],
       NULL AS [srcSchema],
       NULL AS [srcObject],
       NULL AS KeyColumns,
       NULL AS [DateColumn]
FROM [flw].[DataSubscriber] ds;
GO
