using System.Collections.Generic;

namespace SQLFlowCore.Utils.Period
{
    /// <summary>
    /// Represents a mapping of countries to their respective seasons.
    /// </summary>
    /// <remarks>
    /// This class contains a static dictionary that maps country names to another dictionary.
    /// The inner dictionary maps the month number to the corresponding season in that country.
    /// Currently, it includes mappings for Norway and the United States.
    /// </remarks>
    public class Country
    {
        /// <summary>
        /// Represents a mapping between countries and their respective seasons per month.
        /// The outer dictionary uses the country name as the key and an inner dictionary as the value.
        /// The inner dictionary uses the month (represented as an integer from 1 to 12) as the key and the corresponding season as the value.
        /// </summary>
        public static readonly Dictionary<string, Dictionary<int, string>> CountrySeasonMap = new()
        {
            {
                "Norway", new Dictionary<int, string>
                {
                    { 12, "Vinter" }, // Winter
                    { 1, "Vinter" },
                    { 2, "Vinter" },
                    { 3, "Vår" },     // Spring
                    { 4, "Vår" },
                    { 5, "Vår" },
                    { 6, "Sommer" },  // Summer
                    { 7, "Sommer" },
                    { 8, "Sommer" },
                    { 9, "Høst" },    // Autumn/Fall
                    { 10, "Høst" },
                    { 11, "Høst" }
                }
            },
            {
                "United States", new Dictionary<int, string>
                {
                    { 12, "Winter" },
                    { 1, "Winter" },
                    { 2, "Winter" },
                    { 3, "Spring" },
                    { 4, "Spring" },
                    { 5, "Spring" },
                    { 6, "Summer" },
                    { 7, "Summer" },
                    { 8, "Summer" },
                    { 9, "Fall" },
                    { 10, "Fall" },
                    { 11, "Fall" }
                }
            }
        };

        /// <summary>
        /// Represents a mapping of country names to their respective Google Calendar holiday calendar identifiers.
        /// </summary>
        /// <remarks>
        /// This dictionary is used to fetch the holiday calendar for a specific country from Google Calendar.
        /// The keys are the names of the countries and the values are the identifiers of the respective Google Calendar holiday calendars.
        /// </remarks>
        public static Dictionary<string, string> GoogleCountryHoliday = new()
        {
            {"Christian Holidays","en.christian%23holiday%40group.v.calendar.google.com"},
            {"Jewish Holidays","en.judaism%23holiday%40group.v.calendar.google.com"},
            {"Muslim Holidays","en.islamic%23holiday%40group.v.calendar.google.com"},
            {"Orthodox Holidays","en.orthodox_christianity%23holiday%40group.v.calendar.google.com"},
            {"Afghanistan","en.af%23holiday%40group.v.calendar.google.com"},
            {"Albania","en.al%23holiday%40group.v.calendar.google.com"},
            {"Algeria","en.dz%23holiday%40group.v.calendar.google.com"},
            {"American Samoa","en.as%23holiday%40group.v.calendar.google.com"},
            {"Andorra","en.ad%23holiday%40group.v.calendar.google.com"},
            {"Angola","en.ao%23holiday%40group.v.calendar.google.com"},
            {"Anguilla","en.ai%23holiday%40group.v.calendar.google.com"},
            {"Antigua and Barbuda","en.ag%23holiday%40group.v.calendar.google.com"},
            {"Argentina","en.ar%23holiday%40group.v.calendar.google.com"},
            {"Armenia","en.am%23holiday%40group.v.calendar.google.com"},
            {"Aruba","en.aw%23holiday%40group.v.calendar.google.com"},
            {"Australia","en.australian%23holiday%40group.v.calendar.google.com"},
            {"Austria","en.austrian%23holiday%40group.v.calendar.google.com"},
            {"Azerbaijan","en.az%23holiday%40group.v.calendar.google.com"},
            {"Bahamas","en.bs%23holiday%40group.v.calendar.google.com"},
            {"Bahrain","en.bh%23holiday%40group.v.calendar.google.com"},
            {"Bangladesh","en.bd%23holiday%40group.v.calendar.google.com"},
            {"Barbados","en.bb%23holiday%40group.v.calendar.google.com"},
            {"Belarus","en.by%23holiday%40group.v.calendar.google.com"},
            {"Belgium","en.be%23holiday%40group.v.calendar.google.com"},
            {"Belize","en.bz%23holiday%40group.v.calendar.google.com"},
            {"Benin","en.bj%23holiday%40group.v.calendar.google.com"},
            {"Bermuda","en.bm%23holiday%40group.v.calendar.google.com"},
            {"Bhutan","en.bt%23holiday%40group.v.calendar.google.com"},
            {"Bolivia","en.bo%23holiday%40group.v.calendar.google.com"},
            {"Bosnia and Herzegovina","en.ba%23holiday%40group.v.calendar.google.com"},
            {"Botswana","en.bw%23holiday%40group.v.calendar.google.com"},
            {"Brazil","en.brazilian%23holiday%40group.v.calendar.google.com"},
            {"British Virgin Islands","en.vg%23holiday%40group.v.calendar.google.com"},
            {"Brunei Darussalam","en.bn%23holiday%40group.v.calendar.google.com"},
            {"Bulgaria","en.bulgarian%23holiday%40group.v.calendar.google.com"},
            {"Burkina Faso","en.bf%23holiday%40group.v.calendar.google.com"},
            {"Burundi","en.bi%23holiday%40group.v.calendar.google.com"},
            {"Cambodia","en.kh%23holiday%40group.v.calendar.google.com"},
            {"Cameroon","en.cm%23holiday%40group.v.calendar.google.com"},
            {"Canada","en.canadian%23holiday%40group.v.calendar.google.com"},
            {"Cape Verde","en.cv%23holiday%40group.v.calendar.google.com"},
            {"Cayman Islands","en.ky%23holiday%40group.v.calendar.google.com"},
            {"Central African Reinternal","en.cf%23holiday%40group.v.calendar.google.com"},
            {"Chad","en.td%23holiday%40group.v.calendar.google.com"},
            {"Chile","en.cl%23holiday%40group.v.calendar.google.com"},
            {"China","en.china%23holiday%40group.v.calendar.google.com"},
            {"Colombia","en.co%23holiday%40group.v.calendar.google.com"},
            {"Comoros","en.km%23holiday%40group.v.calendar.google.com"},
            {"Congo","en.cg%23holiday%40group.v.calendar.google.com"},
            {"Cook Islands","en.ck%23holiday%40group.v.calendar.google.com"},
            {"Costa Rica","en.cr%23holiday%40group.v.calendar.google.com"},
            {"Côte d'Ivoire","en.ci%23holiday%40group.v.calendar.google.com"},
            {"Croatia","en.croatian%23holiday%40group.v.calendar.google.com"},
            {"Cuba","en.cu%23holiday%40group.v.calendar.google.com"},
            {"Curaçao","en.cw%23holiday%40group.v.calendar.google.com"},
            {"Cyprus","en.cy%23holiday%40group.v.calendar.google.com"},
            {"Czechia","en.czech%23holiday%40group.v.calendar.google.com"},
            {"Democratic People's Reinternal of Korea","en.kp%23holiday%40group.v.calendar.google.com"},
            {"Denmark","en.danish%23holiday%40group.v.calendar.google.com"},
            {"Djibouti","en.dj%23holiday%40group.v.calendar.google.com"},
            {"Dominica","en.dm%23holiday%40group.v.calendar.google.com"},
            {"Dominican Reinternal","en.do%23holiday%40group.v.calendar.google.com"},
            {"Ecuador","en.ec%23holiday%40group.v.calendar.google.com"},
            {"Egypt","en.eg%23holiday%40group.v.calendar.google.com"},
            {"El Salvador","en.sv%23holiday%40group.v.calendar.google.com"},
            {"Equatorial Guinea","en.gq%23holiday%40group.v.calendar.google.com"},
            {"Eritrea","en.er%23holiday%40group.v.calendar.google.com"},
            {"Estonia","en.ee%23holiday%40group.v.calendar.google.com"},
            {"Ethiopia","en.et%23holiday%40group.v.calendar.google.com"},
            {"Falkland Islands (Malvinas)","en.fk%23holiday%40group.v.calendar.google.com"},
            {"Faroe Islands","en.fo%23holiday%40group.v.calendar.google.com"},
            {"Federated States of Micronesia","en.fm%23holiday%40group.v.calendar.google.com"},
            {"Fiji","en.fj%23holiday%40group.v.calendar.google.com"},
            {"Finland","en.finnish%23holiday%40group.v.calendar.google.com"},
            {"France","en.french%23holiday%40group.v.calendar.google.com"},
            {"French Guiana","en.gf%23holiday%40group.v.calendar.google.com"},
            {"French Polynesia","en.pf%23holiday%40group.v.calendar.google.com"},
            {"Gabon","en.ga%23holiday%40group.v.calendar.google.com"},
            {"Gambia","en.gm%23holiday%40group.v.calendar.google.com"},
            {"Georgia","en.ge%23holiday%40group.v.calendar.google.com"},
            {"Germany","en.german%23holiday%40group.v.calendar.google.com"},
            {"Ghana","en.gh%23holiday%40group.v.calendar.google.com"},
            {"Gibraltar","en.gi%23holiday%40group.v.calendar.google.com"},
            {"Greece","en.greek%23holiday%40group.v.calendar.google.com"},
            {"Greenland","en.gl%23holiday%40group.v.calendar.google.com"},
            {"Grenada","en.gd%23holiday%40group.v.calendar.google.com"},
            {"Guam","en.gu%23holiday%40group.v.calendar.google.com"},
            {"Guatemala","en.gt%23holiday%40group.v.calendar.google.com"},
            {"Guernsey","en.gg%23holiday%40group.v.calendar.google.com"},
            {"Guinea","en.gn%23holiday%40group.v.calendar.google.com"},
            {"Guinea-Bissau","en.gw%23holiday%40group.v.calendar.google.com"},
            {"Guyana","en.gy%23holiday%40group.v.calendar.google.com"},
            {"Haiti","en.ht%23holiday%40group.v.calendar.google.com"},
            {"Holy See (Vatican City State)","en.va%23holiday%40group.v.calendar.google.com"},
            {"Honduras","en.hn%23holiday%40group.v.calendar.google.com"},
            {"Hong Kong","en.hong_kong%23holiday%40group.v.calendar.google.com"},
            {"Hungary","en.hungarian%23holiday%40group.v.calendar.google.com"},
            {"Iceland","en.is%23holiday%40group.v.calendar.google.com"},
            {"India","en.indian%23holiday%40group.v.calendar.google.com"},
            {"Indonesia","en.indonesian%23holiday%40group.v.calendar.google.com"},
            {"Iraq","en.iq%23holiday%40group.v.calendar.google.com"},
            {"Ireland","en.irish%23holiday%40group.v.calendar.google.com"},
            {"Islamic Reinternal of Iran","en.ir%23holiday%40group.v.calendar.google.com"},
            {"Isle of Man","en.im%23holiday%40group.v.calendar.google.com"},
            {"Israel","en.jewish%23holiday%40group.v.calendar.google.com"},
            {"Italy","en.italian%23holiday%40group.v.calendar.google.com"},
            {"Jamaica","en.jm%23holiday%40group.v.calendar.google.com"},
            {"Japan","en.japanese%23holiday%40group.v.calendar.google.com"},
            {"Jersey","en.je%23holiday%40group.v.calendar.google.com"},
            {"Jordan","en.jo%23holiday%40group.v.calendar.google.com"},
            {"Kazakhstan","en.kz%23holiday%40group.v.calendar.google.com"},
            {"Kenya","en.ke%23holiday%40group.v.calendar.google.com"},
            {"Kiribati","en.ki%23holiday%40group.v.calendar.google.com"},
            {"Kuwait","en.kw%23holiday%40group.v.calendar.google.com"},
            {"Kyrgyzstan","en.kg%23holiday%40group.v.calendar.google.com"},
            {"Lao People's Democratic Reinternal","en.la%23holiday%40group.v.calendar.google.com"},
            {"Latvia","en.latvian%23holiday%40group.v.calendar.google.com"},
            {"Lebanon","en.lb%23holiday%40group.v.calendar.google.com"},
            {"Lesotho","en.ls%23holiday%40group.v.calendar.google.com"},
            {"Liberia","en.lr%23holiday%40group.v.calendar.google.com"},
            {"Libya","en.ly%23holiday%40group.v.calendar.google.com"},
            {"Liechtenstein","en.li%23holiday%40group.v.calendar.google.com"},
            {"Lithuania","en.lithuanian%23holiday%40group.v.calendar.google.com"},
            {"Luxembourg","en.lu%23holiday%40group.v.calendar.google.com"},
            {"Macao","en.mo%23holiday%40group.v.calendar.google.com"},
            {"Madagascar","en.mg%23holiday%40group.v.calendar.google.com"},
            {"Malawi","en.mw%23holiday%40group.v.calendar.google.com"},
            {"Malaysia","en.malaysia%23holiday%40group.v.calendar.google.com"},
            {"Maldives","en.mv%23holiday%40group.v.calendar.google.com"},
            {"Mali","en.ml%23holiday%40group.v.calendar.google.com"},
            {"Malta","en.mt%23holiday%40group.v.calendar.google.com"},
            {"Marshall Islands","en.mh%23holiday%40group.v.calendar.google.com"},
            {"Martinique","en.mq%23holiday%40group.v.calendar.google.com"},
            {"Mauritania","en.mr%23holiday%40group.v.calendar.google.com"},
            {"Mauritius","en.mu%23holiday%40group.v.calendar.google.com"},
            {"Mayotte","en.yt%23holiday%40group.v.calendar.google.com"},
            {"Mexico","en.mexican%23holiday%40group.v.calendar.google.com"},
            {"Moldova","en.md%23holiday%40group.v.calendar.google.com"},
            {"Monaco","en.mc%23holiday%40group.v.calendar.google.com"},
            {"Mongolia","en.mn%23holiday%40group.v.calendar.google.com"},
            {"Montenegro","en.me%23holiday%40group.v.calendar.google.com"},
            {"Montserrat","en.ms%23holiday%40group.v.calendar.google.com"},
            {"Morocco","en.ma%23holiday%40group.v.calendar.google.com"},
            {"Mozambique","en.mz%23holiday%40group.v.calendar.google.com"},
            {"Myanmar","en.mm%23holiday%40group.v.calendar.google.com"},
            {"Namibia","en.na%23holiday%40group.v.calendar.google.com"},
            {"Nauru","en.nr%23holiday%40group.v.calendar.google.com"},
            {"Nepal","en.np%23holiday%40group.v.calendar.google.com"},
            {"Netherlands","en.dutch%23holiday%40group.v.calendar.google.com"},
            {"New Caledonia","en.nc%23holiday%40group.v.calendar.google.com"},
            {"New Zealand","en.new_zealand%23holiday%40group.v.calendar.google.com"},
            {"Nicaragua","en.ni%23holiday%40group.v.calendar.google.com"},
            {"Niger","en.ne%23holiday%40group.v.calendar.google.com"},
            {"Nigeria","en.ng%23holiday%40group.v.calendar.google.com"},
            {"Northern Mariana Islands","en.mp%23holiday%40group.v.calendar.google.com"},
            {"Norway","no.norwegian%23holiday%40group.v.calendar.google.com"},
            {"Oman","en.om%23holiday%40group.v.calendar.google.com"},
            {"Pakistan","en.pk%23holiday%40group.v.calendar.google.com"},
            {"Palau","en.pw%23holiday%40group.v.calendar.google.com"},
            {"Panama","en.pa%23holiday%40group.v.calendar.google.com"},
            {"Papua New Guinea","en.pg%23holiday%40group.v.calendar.google.com"},
            {"Paraguay","en.py%23holiday%40group.v.calendar.google.com"},
            {"Peru","en.pe%23holiday%40group.v.calendar.google.com"},
            {"Philippines","en.philippines%23holiday%40group.v.calendar.google.com"},
            {"Poland","en.polish%23holiday%40group.v.calendar.google.com"},
            {"Portugal","en.portuguese%23holiday%40group.v.calendar.google.com"},
            {"Puerto Rico","en.pr%23holiday%40group.v.calendar.google.com"},
            {"Qatar","en.qa%23holiday%40group.v.calendar.google.com"},
            {"Reinternal of Korea","en.south_korea%23holiday%40group.v.calendar.google.com"},
            {"Réunion","en.re%23holiday%40group.v.calendar.google.com"},
            {"Romania","en.romanian%23holiday%40group.v.calendar.google.com"},
            {"Russian Federation","en.russian%23holiday%40group.v.calendar.google.com"},
            {"Rwanda","en.rw%23holiday%40group.v.calendar.google.com"},
            {"Saint Barthélemy","en.bl%23holiday%40group.v.calendar.google.com"},
            {"Saint Helena","en.sh%23holiday%40group.v.calendar.google.com"},
            {"Saint Kitts and Nevis","en.kn%23holiday%40group.v.calendar.google.com"},
            {"Saint Lucia","en.lc%23holiday%40group.v.calendar.google.com"},
            {"Saint Martin (French part)","en.mf%23holiday%40group.v.calendar.google.com"},
            {"Saint Pierre and Miquelon","en.pm%23holiday%40group.v.calendar.google.com"},
            {"Saint Vincent and the Grenadines","en.vc%23holiday%40group.v.calendar.google.com"},
            {"Samoa","en.ws%23holiday%40group.v.calendar.google.com"},
            {"San Marino","en.sm%23holiday%40group.v.calendar.google.com"},
            {"Sao Tome and Principe","en.st%23holiday%40group.v.calendar.google.com"},
            {"Saudi Arabia","en.saudiarabian%23holiday%40group.v.calendar.google.com"},
            {"Senegal","en.sn%23holiday%40group.v.calendar.google.com"},
            {"Serbia","en.rs%23holiday%40group.v.calendar.google.com"},
            {"Seychelles","en.sc%23holiday%40group.v.calendar.google.com"},
            {"Sierra Leone","en.sl%23holiday%40group.v.calendar.google.com"},
            {"Singapore","en.singapore%23holiday%40group.v.calendar.google.com"},
            {"Sint Maarten (Dutch part)","en.sx%23holiday%40group.v.calendar.google.com"},
            {"Slovakia","en.slovak%23holiday%40group.v.calendar.google.com"},
            {"Slovenia","en.slovenian%23holiday%40group.v.calendar.google.com"},
            {"Solomon Islands","en.sb%23holiday%40group.v.calendar.google.com"},
            {"Somalia","en.so%23holiday%40group.v.calendar.google.com"},
            {"South Africa","en.sa%23holiday%40group.v.calendar.google.com"},
            {"South Sudan","en.ss%23holiday%40group.v.calendar.google.com"},
            {"Spain","en.spain%23holiday%40group.v.calendar.google.com"},
            {"Sri Lanka","en.lk%23holiday%40group.v.calendar.google.com"},
            {"Sudan","en.sd%23holiday%40group.v.calendar.google.com"},
            {"Suriname","en.sr%23holiday%40group.v.calendar.google.com"},
            {"Swaziland","en.sz%23holiday%40group.v.calendar.google.com"},
            {"Sweden","en.swedish%23holiday%40group.v.calendar.google.com"},
            {"Switzerland","en.ch%23holiday%40group.v.calendar.google.com"},
            {"Syrian Arab Reinternal","en.sy%23holiday%40group.v.calendar.google.com"},
            {"Taiwan","en.taiwan%23holiday%40group.v.calendar.google.com"},
            {"Tajikistan","en.tj%23holiday%40group.v.calendar.google.com"},
            {"Thailand","en.th%23holiday%40group.v.calendar.google.com"},
            {"The Democratic Reinternal of the Congo","en.cd%23holiday%40group.v.calendar.google.com"},
            {"The Former Yugoslav Reinternal of Macedonia","en.mk%23holiday%40group.v.calendar.google.com"},
            {"Timor-Leste","en.tl%23holiday%40group.v.calendar.google.com"},
            {"Togo","en.tg%23holiday%40group.v.calendar.google.com"},
            {"Tonga","en.to%23holiday%40group.v.calendar.google.com"},
            {"Trinidad and Tobago","en.tt%23holiday%40group.v.calendar.google.com"},
            {"Tunisia","en.tn%23holiday%40group.v.calendar.google.com"},
            {"Turkey","en.turkish%23holiday%40group.v.calendar.google.com"},
            {"Turkmenistan","en.tm%23holiday%40group.v.calendar.google.com"},
            {"Turks and Caicos Islands","en.tc%23holiday%40group.v.calendar.google.com"},
            {"Tuvalu","en.tv%23holiday%40group.v.calendar.google.com"},
            {"U.S. Virgin Islands","en.vi%23holiday%40group.v.calendar.google.com"},
            {"Uganda","en.ug%23holiday%40group.v.calendar.google.com"},
            {"Ukraine","en.ukrainian%23holiday%40group.v.calendar.google.com"},
            {"United Arab Emirates","en.ae%23holiday%40group.v.calendar.google.com"},
            {"United Kingdom","en.uk%23holiday%40group.v.calendar.google.com"},
            {"United Reinternal of Tanzania","en.tz%23holiday%40group.v.calendar.google.com"},
            {"United States","en.usa%23holiday%40group.v.calendar.google.com"},
            {"Uruguay","en.uy%23holiday%40group.v.calendar.google.com"},
            {"Uzbekistan","en.uz%23holiday%40group.v.calendar.google.com"},
            {"Vanuatu","en.vu%23holiday%40group.v.calendar.google.com"},
            {"Venezuela","en.ve%23holiday%40group.v.calendar.google.com"},
            {"Vietnam","en.vietnamese%23holiday%40group.v.calendar.google.com"},
            {"Wallis and Futuna","en.wf%23holiday%40group.v.calendar.google.com"},
            {"Yemen","en.ye%23holiday%40group.v.calendar.google.com"},
            {"Zambia","en.zm%23holiday%40group.v.calendar.google.com"},
            {"Zimbabwe","en.zw%23holiday%40group.v.calendar.google.com"}
        };

        /// <summary>
        /// Represents a mapping between country names and their corresponding culture codes.
        /// </summary>
        /// <remarks>
        /// This field is used to map a country to its culture code (language code), which can be used for localization purposes.
        /// Each key-value pair in the dictionary represents a country and its corresponding culture code.
        /// For example, the key "United States" maps to the value "en-US", which stands for English (United States).
        /// </remarks>
        internal static Dictionary<string, string> CountryToCulture = new()
        {
            {"Afghanistan","af"},
            {"Albania","sq"},
            {"Algeria","ar-DZ"},
            {"Argentina","es-AR"},
            {"Armenia","hy"},
            {"Australia","en-AU"},
            {"Austria","de-AT"},
            {"Azerbaijan","az"},
            {"Bahrain","ar-BH"},
            {"Bangladesh","bn-BD"},
            {"Belarus","be"},
            {"Belgium","nl-BE"},
            {"Bolivia","es-BO"},
            {"Bosnia and Herzegovina","bs-BA"},
            {"Brazil","pt-BR"},
            {"Bulgaria","bg"},
            {"Canada","en-CA"},
            {"Chile","es-CL"},
            {"China","zh-CN"},
            {"Colombia","es-CO"},
            {"Costa Rica","es-CR"},
            {"Croatia","hr"},
            {"Czechia","cs"},
            {"Denmark","da"},
            {"Dominican Reinternal","es-DO"},
            {"Ecuador","es-EC"},
            {"Egypt","ar-EG"},
            {"El Salvador","es-SV"},
            {"Estonia","et"},
            {"Ethiopia","am"},
            {"Finland","fi"},
            {"France","fr-FR"},
            {"Germany","de-DE"},
            {"Greece","el-GR"},
            {"Guatemala","es-GT"},
            {"Honduras","es-HN"},
            {"Hong Kong","zh-HK"},
            {"Hungary","hu"},
            {"Iceland","is"},
            {"India","hi-IN"},
            {"Indonesia","id"},
            {"Iran","fa"},
            {"Iraq","ar-IQ"},
            {"Ireland","en-IE"},
            {"Israel","he"},
            {"Italy","it-IT"},
            {"Japan","ja-JP"},
            {"Jordan","ar-JO"},
            {"Kazakhstan","kk"},
            {"Kenya","sw-KE"},
            {"Korea","ko-KR"},
            {"Kuwait","ar-KW"},
            {"Latvia","lv"},
            {"Lebanon","ar-LB"},
            {"Libya","ar-LY"},
            {"Lithuania","lt"},
            {"Luxembourg","lb"},
            {"Malaysia","ms-MY"},
            {"Mexico","es-MX"},
            {"Morocco","ar-MA"},
            {"Netherlands","nl-NL"},
            {"New Zealand","en-NZ"},
            {"Nicaragua","es-NI"},
            {"Nigeria","yo-NG"},
            {"Norway","nb-NO"},
            {"Oman","ar-OM"},
            {"Pakistan","ur-PK"},
            {"Panama","es-PA"},
            {"Paraguay","es-PY"},
            {"Peru","es-PE"},
            {"Philippines","fil-PH"},
            {"Poland","pl-PL"},
            {"Portugal","pt-PT"},
            {"Puerto Rico","es-PR"},
            {"Qatar","ar-QA"},
            {"Romania","ro-RO"},
            {"Russia","ru-RU"},
            {"Saudi Arabia","ar-SA"},
            {"Serbia","sr-Latn-CS"},
            {"Singapore","en-SG"},
            {"Slovakia","sk"},
            {"Slovenia","sl"},
            {"South Africa","af-ZA"},
            {"Spain","es-ES"},
            {"Sri Lanka","si-LK"},
            {"Sweden","sv-SE"},
            {"Switzerland","de-CH"},
            {"Syrian Arab Reinternal","ar-SY"},
            {"Taiwan","zh-TW"},
            {"Tajikistan","tg"},
            {"Thailand","th"},
            {"Tunisia","ar-TN"},
            {"Turkey","tr-TR"},
            {"Turkmenistan","tk"},
            {"Ukraine","uk"},
            {"United Arab Emirates","ar-AE"},
            {"United Kingdom","en-GB"},
            {"United States","en-US"},
            {"Uruguay","es-UY"},
            {"Uzbekistan","uz"},
            {"Venezuela","es-VE"},
            {"Vietnam","vi"},
            {"Yemen","ar-YE"},
            {"Zimbabwe","sn"}
    };

        /// <summary>
        /// Represents a dictionary of country names mapped to their respective ISO 3166-1 alpha-2 codes.
        /// </summary>
        public static Dictionary<string, string> CountryIso3166Alpha2 = new()
        {
            {"AF","Afghanistan"},
            {"AL","Albania"},
            {"DZ","Algeria"},
            {"AS","American Samoa"},
            {"AD","Andorra"},
            {"AO","Angola"},
            {"AI","Anguilla"},
            {"AQ","Antarctica"},
            {"AG","Antigua and Barbuda"},
            {"AR","Argentina"},
            {"AM","Armenia"},
            {"AW","Aruba"},
            {"AU","Australia"},
            {"AT","Austria"},
            {"AZ","Azerbaijan"},
            {"BS","Bahamas (the)"},
            {"BH","Bahrain"},
            {"BD","Bangladesh"},
            {"BB","Barbados"},
            {"BY","Belarus"},
            {"BE","Belgium"},
            {"BZ","Belize"},
            {"BJ","Benin"},
            {"BM","Bermuda"},
            {"AX","Åland Islands"},
            {"BT","Bhutan"},
            {"BO","Bolivia (Plurinational State of)"},
            {"BQ","Bonaire, Sint Eustatius and Saba"},
            {"BA","Bosnia and Herzegovina"},
            {"BW","Botswana"},
            {"BV","Bouvet Island"},
            {"BR","Brazil"},
            {"IO","British Indian Ocean Territory (the)"},
            {"BN","Brunei Darussalam"},
            {"BG","Bulgaria"},
            {"BF","Burkina Faso"},
            {"BI","Burundi"},
            {"CV","Cabo Verde"},
            {"KH","Cambodia"},
            {"CM","Cameroon"},
            {"CA","Canada"},
            {"KY","Cayman Islands (the)"},
            {"CF","Central African Reinternal (the)"},
            {"TD","Chad"},
            {"CL","Chile"},
            {"CN","China"},
            {"CX","Christmas Island"},
            {"CC","Cocos (Keeling) Islands (the)"},
            {"CO","Colombia"},
            {"KM","Comoros (the)"},
            {"CD","Congo (the Democratic Reinternal of the)"},
            {"CG","Congo (the)"},
            {"CK","Cook Islands (the)"},
            {"CR","Costa Rica"},
            {"HR","Croatia"},
            {"CU","Cuba"},
            {"CW","Curaçao"},
            {"CY","Cyprus"},
            {"CZ","Czechia"},
            {"CI","Côte d'Ivoire"},
            {"DK","Denmark"},
            {"DJ","Djibouti"},
            {"DM","Dominica"},
            {"DO","Dominican Reinternal (the)"},
            {"EC","Ecuador"},
            {"EG","Egypt"},
            {"SV","El Salvador"},
            {"GQ","Equatorial Guinea"},
            {"ER","Eritrea"},
            {"EE","Estonia"},
            {"SZ","Eswatini"},
            {"ET","Ethiopia"},
            {"FK","Falkland Islands (the) [Malvinas]"},
            {"FO","Faroe Islands (the)"},
            {"FJ","Fiji"},
            {"FI","Finland"},
            {"FR","France"},
            {"GF","French Guiana"},
            {"PF","French Polynesia"},
            {"TF","French Southern Territories (the)"},
            {"GA","Gabon"},
            {"GM","Gambia (the)"},
            {"GE","Georgia"},
            {"DE","Germany"},
            {"GH","Ghana"},
            {"GI","Gibraltar"},
            {"GR","Greece"},
            {"GL","Greenland"},
            {"GD","Grenada"},
            {"GP","Guadeloupe"},
            {"GU","Guam"},
            {"GT","Guatemala"},
            {"GG","Guernsey"},
            {"GN","Guinea"},
            {"GW","Guinea-Bissau"},
            {"GY","Guyana"},
            {"HT","Haiti"},
            {"HM","Heard Island and McDonald Islands"},
            {"VA","Holy See (the)"},
            {"HN","Honduras"},
            {"HK","Hong Kong"},
            {"HU","Hungary"},
            {"IS","Iceland"},
            {"IN","India"},
            {"ID","Indonesia"},
            {"IR","Iran (Islamic Reinternal of)"},
            {"IQ","Iraq"},
            {"IE","Ireland"},
            {"IM","Isle of Man"},
            {"IL","Israel"},
            {"IT","Italy"},
            {"JM","Jamaica"},
            {"JP","Japan"},
            {"JE","Jersey"},
            {"JO","Jordan"},
            {"KZ","Kazakhstan"},
            {"KE","Kenya"},
            {"KI","Kiribati"},
            {"KP","Korea (the Democratic People's Reinternal of)"},
            {"KR","Korea (the Reinternal of)"},
            {"KW","Kuwait"},
            {"KG","Kyrgyzstan"},
            {"LA","Lao People's Democratic Reinternal (the)"},
            {"LV","Latvia"},
            {"LB","Lebanon"},
            {"LS","Lesotho"},
            {"LR","Liberia"},
            {"LY","Libya"},
            {"LI","Liechtenstein"},
            {"LT","Lithuania"},
            {"LU","Luxembourg"},
            {"MO","Macao"},
            {"MG","Madagascar"},
            {"MW","Malawi"},
            {"MY","Malaysia"},
            {"MV","Maldives"},
            {"ML","Mali"},
            {"MT","Malta"},
            {"MH","Marshall Islands (the)"},
            {"MQ","Martinique"},
            {"MR","Mauritania"},
            {"MU","Mauritius"},
            {"YT","Mayotte"},
            {"MX","Mexico"},
            {"FM","Micronesia (Federated States of)"},
            {"MD","Moldova (the Reinternal of)"},
            {"MC","Monaco"},
            {"MN","Mongolia"},
            {"ME","Montenegro"},
            {"MS","Montserrat"},
            {"MA","Morocco"},
            {"MZ","Mozambique"},
            {"MM","Myanmar"},
            {"NA","Namibia"},
            {"NR","Nauru"},
            {"NP","Nepal"},
            {"NL","Netherlands (Kingdom of the)"},
            {"NC","New Caledonia"},
            {"NZ","New Zealand"},
            {"NI","Nicaragua"},
            {"NE","Niger (the)"},
            {"NG","Nigeria"},
            {"NU","Niue"},
            {"NF","Norfolk Island"},
            {"MK","North Macedonia"},
            {"MP","Northern Mariana Islands (the)"},
            {"NO","Norway"},
            {"OM","Oman"},
            {"PK","Pakistan"},
            {"PW","Palau"},
            {"PS","Palestine, State of"},
            {"PA","Panama"},
            {"PG","Papua New Guinea"},
            {"PY","Paraguay"},
            {"PE","Peru"},
            {"PH","Philippines (the)"},
            {"PN","Pitcairn"},
            {"PL","Poland"},
            {"PT","Portugal"},
            {"PR","Puerto Rico"},
            {"QA","Qatar"},
            {"RO","Romania"},
            {"RU","Russian Federation (the)"},
            {"RW","Rwanda"},
            {"RE","Réunion"},
            {"BL","Saint Barthélemy"},
            {"SH","Saint Helena, Ascension and Tristan da Cunha"},
            {"KN","Saint Kitts and Nevis"},
            {"LC","Saint Lucia"},
            {"MF","Saint Martin (French part)"},
            {"PM","Saint Pierre and Miquelon"},
            {"VC","Saint Vincent and the Grenadines"},
            {"WS","Samoa"},
            {"SM","San Marino"},
            {"ST","Sao Tome and Principe"},
            {"SA","Saudi Arabia"},
            {"SN","Senegal"},
            {"RS","Serbia"},
            {"SC","Seychelles"},
            {"SL","Sierra Leone"},
            {"SG","Singapore"},
            {"SX","Sint Maarten (Dutch part)"},
            {"SK","Slovakia"},
            {"SI","Slovenia"},
            {"SB","Solomon Islands"},
            {"SO","Somalia"},
            {"ZA","South Africa"},
            {"GS","South Georgia and the South Sandwich Islands"},
            {"SS","South Sudan"},
            {"ES","Spain"},
            {"LK","Sri Lanka"},
            {"SD","Sudan (the)"},
            {"SR","Suriname"},
            {"SJ","Svalbard and Jan Mayen"},
            {"SE","Sweden"},
            {"CH","Switzerland"},
            {"SY","Syrian Arab Reinternal (the)"},
            {"TW","Taiwan (Province of China)"},
            {"TJ","Tajikistan"},
            {"TZ","Tanzania, the United Reinternal of"},
            {"TH","Thailand"},
            {"TL","Timor-Leste"},
            {"TG","Togo"},
            {"TK","Tokelau"},
            {"TO","Tonga"},
            {"TT","Trinidad and Tobago"},
            {"TN","Tunisia"},
            {"TM","Turkmenistan"},
            {"TC","Turks and Caicos Islands (the)"},
            {"TV","Tuvalu"},
            {"TR","Türkiye"},
            {"UG","Uganda"},
            {"UA","Ukraine"},
            {"AE","United Arab Emirates (the)"},
            {"GB","United Kingdom of Great Britain and Northern Ireland (the)"},
            {"UM","United States Minor Outlying Islands (the)"},
            {"US","United States of America (the)"},
            {"UY","Uruguay"},
            {"UZ","Uzbekistan"},
            {"VU","Vanuatu"},
            {"VE","Venezuela (Bolivarian Reinternal of)"},
            {"VN","Viet Nam"},
            {"VG","Virgin Islands (British)"},
            {"VI","Virgin Islands (U.S.)"},
            {"WF","Wallis and Futuna"},
            {"EH","Western Sahara*"},
            {"YE","Yemen"},
            {"ZM","Zambia"},
            {"ZW","Zimbabwe"}

        };

        /// <summary>
        /// Represents a mapping between ISO 3166-1 alpha-3 country codes and country names.
        /// </summary>
        /// <remarks>
        /// The ISO 3166-1 alpha-3 codes are three-letter country codes defined in ISO 3166-1, part of the ISO 3166 standard
        /// published by the International Organization for Standardization (ISO), to represent countries, dependent territories,
        /// and special areas of geographical interest.
        /// </remarks>
        public static Dictionary<string, string> CountryIso3166Alpha3 = new()
        {
            {"AFG","Afghanistan"},
            {"ALB","Albania"},
            {"DZA","Algeria"},
            {"ASM","American Samoa"},
            {"AND","Andorra"},
            {"AGO","Angola"},
            {"AIA","Anguilla"},
            {"ATA","Antarctica"},
            {"ATG","Antigua and Barbuda"},
            {"ARG","Argentina"},
            {"ARM","Armenia"},
            {"ABW","Aruba"},
            {"AUS","Australia"},
            {"AUT","Austria"},
            {"AZE","Azerbaijan"},
            {"BHS","Bahamas (the)"},
            {"BHR","Bahrain"},
            {"BGD","Bangladesh"},
            {"BRB","Barbados"},
            {"BLR","Belarus"},
            {"BEL","Belgium"},
            {"BLZ","Belize"},
            {"BEN","Benin"},
            {"BMU","Bermuda"},
            {"ALA","Åland Islands"},
            {"BTN","Bhutan"},
            {"BOL","Bolivia (Plurinational State of)"},
            {"BES","Bonaire, Sint Eustatius and Saba"},
            {"BIH","Bosnia and Herzegovina"},
            {"BWA","Botswana"},
            {"BVT","Bouvet Island"},
            {"BRA","Brazil"},
            {"IOT","British Indian Ocean Territory (the)"},
            {"BRN","Brunei Darussalam"},
            {"BGR","Bulgaria"},
            {"BFA","Burkina Faso"},
            {"BDI","Burundi"},
            {"CPV","Cabo Verde"},
            {"KHM","Cambodia"},
            {"CMR","Cameroon"},
            {"CAN","Canada"},
            {"CYM","Cayman Islands (the)"},
            {"CAF","Central African Reinternal (the)"},
            {"TCD","Chad"},
            {"CHL","Chile"},
            {"CHN","China"},
            {"CXR","Christmas Island"},
            {"CCK","Cocos (Keeling) Islands (the)"},
            {"COL","Colombia"},
            {"COM","Comoros (the)"},
            {"COD","Congo (the Democratic Reinternal of the)"},
            {"COG","Congo (the)"},
            {"COK","Cook Islands (the)"},
            {"CRI","Costa Rica"},
            {"HRV","Croatia"},
            {"CUB","Cuba"},
            {"CUW","Curaçao"},
            {"CYP","Cyprus"},
            {"CZE","Czechia"},
            {"CIV","Côte d'Ivoire"},
            {"DNK","Denmark"},
            {"DJI","Djibouti"},
            {"DMA","Dominica"},
            {"DOM","Dominican Reinternal (the)"},
            {"ECU","Ecuador"},
            {"EGY","Egypt"},
            {"SLV","El Salvador"},
            {"GNQ","Equatorial Guinea"},
            {"ERI","Eritrea"},
            {"EST","Estonia"},
            {"SWZ","Eswatini"},
            {"ETH","Ethiopia"},
            {"FLK","Falkland Islands (the) [Malvinas]"},
            {"FRO","Faroe Islands (the)"},
            {"FJI","Fiji"},
            {"FIN","Finland"},
            {"FRA","France"},
            {"GUF","French Guiana"},
            {"PYF","French Polynesia"},
            {"ATF","French Southern Territories (the)"},
            {"GAB","Gabon"},
            {"GMB","Gambia (the)"},
            {"GEO","Georgia"},
            {"DEU","Germany"},
            {"GHA","Ghana"},
            {"GIB","Gibraltar"},
            {"GRC","Greece"},
            {"GRL","Greenland"},
            {"GRD","Grenada"},
            {"GLP","Guadeloupe"},
            {"GUM","Guam"},
            {"GTM","Guatemala"},
            {"GGY","Guernsey"},
            {"GIN","Guinea"},
            {"GNB","Guinea-Bissau"},
            {"GUY","Guyana"},
            {"HTI","Haiti"},
            {"HMD","Heard Island and McDonald Islands"},
            {"VAT","Holy See (the)"},
            {"HND","Honduras"},
            {"HKG","Hong Kong"},
            {"HUN","Hungary"},
            {"ISL","Iceland"},
            {"IND","India"},
            {"IDN","Indonesia"},
            {"IRN","Iran (Islamic Reinternal of)"},
            {"IRQ","Iraq"},
            {"IRL","Ireland"},
            {"IMN","Isle of Man"},
            {"ISR","Israel"},
            {"ITA","Italy"},
            {"JAM","Jamaica"},
            {"JPN","Japan"},
            {"JEY","Jersey"},
            {"JOR","Jordan"},
            {"KAZ","Kazakhstan"},
            {"KEN","Kenya"},
            {"KIR","Kiribati"},
            {"PRK","Korea (the Democratic People's Reinternal of)"},
            {"KOR","Korea (the Reinternal of)"},
            {"KWT","Kuwait"},
            {"KGZ","Kyrgyzstan"},
            {"LAO","Lao People's Democratic Reinternal (the)"},
            {"LVA","Latvia"},
            {"LBN","Lebanon"},
            {"LSO","Lesotho"},
            {"LBR","Liberia"},
            {"LBY","Libya"},
            {"LIE","Liechtenstein"},
            {"LTU","Lithuania"},
            {"LUX","Luxembourg"},
            {"MAC","Macao"},
            {"MDG","Madagascar"},
            {"MWI","Malawi"},
            {"MYS","Malaysia"},
            {"MDV","Maldives"},
            {"MLI","Mali"},
            {"MLT","Malta"},
            {"MHL","Marshall Islands (the)"},
            {"MTQ","Martinique"},
            {"MRT","Mauritania"},
            {"MUS","Mauritius"},
            {"MYT","Mayotte"},
            {"MEX","Mexico"},
            {"FSM","Micronesia (Federated States of)"},
            {"MDA","Moldova (the Reinternal of)"},
            {"MCO","Monaco"},
            {"MNG","Mongolia"},
            {"MNE","Montenegro"},
            {"MSR","Montserrat"},
            {"MAR","Morocco"},
            {"MOZ","Mozambique"},
            {"MMR","Myanmar"},
            {"NAM","Namibia"},
            {"NRU","Nauru"},
            {"NPL","Nepal"},
            {"NLD","Netherlands (Kingdom of the)"},
            {"NCL","New Caledonia"},
            {"NZL","New Zealand"},
            {"NIC","Nicaragua"},
            {"NER","Niger (the)"},
            {"NGA","Nigeria"},
            {"NIU","Niue"},
            {"NFK","Norfolk Island"},
            {"MKD","North Macedonia"},
            {"MNP","Northern Mariana Islands (the)"},
            {"NOR","Norway"},
            {"OMN","Oman"},
            {"PAK","Pakistan"},
            {"PLW","Palau"},
            {"PSE","Palestine, State of"},
            {"PAN","Panama"},
            {"PNG","Papua New Guinea"},
            {"PRY","Paraguay"},
            {"PER","Peru"},
            {"PHL","Philippines (the)"},
            {"PCN","Pitcairn"},
            {"POL","Poland"},
            {"PRT","Portugal"},
            {"PRI","Puerto Rico"},
            {"QAT","Qatar"},
            {"ROU","Romania"},
            {"RUS","Russian Federation (the)"},
            {"RWA","Rwanda"},
            {"REU","Réunion"},
            {"BLM","Saint Barthélemy"},
            {"SHN","Saint Helena, Ascension and Tristan da Cunha"},
            {"KNA","Saint Kitts and Nevis"},
            {"LCA","Saint Lucia"},
            {"MAF","Saint Martin (French part)"},
            {"SPM","Saint Pierre and Miquelon"},
            {"VCT","Saint Vincent and the Grenadines"},
            {"WSM","Samoa"},
            {"SMR","San Marino"},
            {"STP","Sao Tome and Principe"},
            {"SAU","Saudi Arabia"},
            {"SEN","Senegal"},
            {"SRB","Serbia"},
            {"SYC","Seychelles"},
            {"SLE","Sierra Leone"},
            {"SGP","Singapore"},
            {"SXM","Sint Maarten (Dutch part)"},
            {"SVK","Slovakia"},
            {"SVN","Slovenia"},
            {"SLB","Solomon Islands"},
            {"SOM","Somalia"},
            {"ZAF","South Africa"},
            {"SGS","South Georgia and the South Sandwich Islands"},
            {"SSD","South Sudan"},
            {"ESP","Spain"},
            {"LKA","Sri Lanka"},
            {"SDN","Sudan (the)"},
            {"SUR","Suriname"},
            {"SJM","Svalbard and Jan Mayen"},
            {"SWE","Sweden"},
            {"CHE","Switzerland"},
            {"SYR","Syrian Arab Reinternal (the)"},
            {"TWN","Taiwan (Province of China)"},
            {"TJK","Tajikistan"},
            {"TZA","Tanzania, the United Reinternal of"},
            {"THA","Thailand"},
            {"TLS","Timor-Leste"},
            {"TGO","Togo"},
            {"TKL","Tokelau"},
            {"TON","Tonga"},
            {"TTO","Trinidad and Tobago"},
            {"TUN","Tunisia"},
            {"TKM","Turkmenistan"},
            {"TCA","Turks and Caicos Islands (the)"},
            {"TUV","Tuvalu"},
            {"TUR","Türkiye"},
            {"UGA","Uganda"},
            {"UKR","Ukraine"},
            {"ARE","United Arab Emirates (the)"},
            {"GBR","United Kingdom of Great Britain and Northern Ireland (the)"},
            {"UMI","United States Minor Outlying Islands (the)"},
            {"USA","United States of America (the)"},
            {"URY","Uruguay"},
            {"UZB","Uzbekistan"},
            {"VUT","Vanuatu"},
            {"VEN","Venezuela (Bolivarian Reinternal of)"},
            {"VNM","Viet Nam"},
            {"VGB","Virgin Islands (British)"},
            {"VIR","Virgin Islands (U.S.)"},
            {"WLF","Wallis and Futuna"},
            {"ESH","Western Sahara*"},
            {"YEM","Yemen"},
            {"ZMB","Zambia"},
            {"ZWE","Zimbabwe"}

        };
    }
}
