SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [flw].[IsSrcTypeFile](@FlowType VARCHAR(25))
RETURNS TABLE
AS
RETURN 
(
    SELECT CASE WHEN @FlowType IN ('csv','jsn','prq','xls','xml')  THEN 1 ELSE 0 END TypeIsFile 
)
GO
