SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [flw].[CreateFultextCatalogs]
AS
BEGIN

CREATE FULLTEXT CATALOG [SQLFlowEvents]
WITH ACCENT_SENSITIVITY = OFF
AS DEFAULT
AUTHORIZATION [dbo]

-- Full Text Catalog Tables

CREATE FULLTEXT INDEX ON [flw].[SysLogFileEvent] KEY INDEX [PK_SysLogFileEvent] ON [SQLFlowEvents]
ALTER FULLTEXT INDEX ON [flw].[SysLogFileEvent] ADD ([FileName_DW] LANGUAGE 0)


CREATE FULLTEXT CATALOG [SQLFlowFTC]
WITH ACCENT_SENSITIVITY = OFF
AUTHORIZATION [dbo]

-- Full Text Catalog Tables
CREATE FULLTEXT INDEX ON [flw].[SysLogFile] KEY INDEX [PK_SysFileLog] ON [SQLFlowFTC]
ALTER FULLTEXT INDEX ON [flw].[SysLogFile] ADD ([FileName_DW] LANGUAGE 0)


END
GO
