CREATE TABLE [flw].[IngestionTokenExp]
(
[TokenExpAlias] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SelectExp] [nvarchar] (2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SelectExpFull] [nvarchar] (2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataType] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Example] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [flw].[IngestionTokenExp] ADD CONSTRAINT [PK_IngestionTokenExp] PRIMARY KEY CLUSTERED ([TokenExpAlias]) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', 'This table hosts metadata about how to tokenize data after the ingestion process has completed successfully. Token values along with original values are pushed to a separate table and the original table values are tokenized. Expression are built using standard T-SQL select expressions.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', NULL, NULL
GO
EXEC sp_addextendedproperty N'MS_Description', 'The column [flw].[IngestionTokenExp].[DataType] stores the data type of the tokenized value generated by the corresponding select expression in the [flw].[IngestionTokenExp].[SelectExp] column. This column is used during the tokenization process to ensure that the correct data type is assigned to each tokenized value. The data types supported by this column are the standard SQL Server data types such as int, varchar, datetime, etc. If no data type is specified, the default data type of the corresponding column in the target table is used.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'DataType'
GO
EXEC sp_addextendedproperty N'MS_Description', 'The column [flw].[IngestionTokenExp].[Description] stores a brief description of the token expression defined in the corresponding row. This description provides additional information about the token expression and its purpose, and can be used to document the intent of the expression for future reference.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'Description'
GO
EXEC sp_addextendedproperty N'MS_Description', 'The [flw].[IngestionTokenExp].[Example] column stores a sample value that can be used to illustrate the expected format of the token values produced by the corresponding SelectExp expression. This column provides a quick reference for the expected output of the expression. For example, if the SelectExp expression generates a token for a date value, the Example column could store a sample date value in the format YYYY-MM-DD to demonstrate the expected format of the token values. The Example column does not enforce any constraints or data validation rules, but it can be used to provide guidance for downstream processing and analysis of the tokenized data.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'Example'
GO
EXEC sp_addextendedproperty N'MS_Description', '[flw].[IngestionTokenExp].[SelectExp] column stores a T-SQL select expression that determines how the data should be tokenized after the ingestion process. The expression should return the token value(s) for the corresponding column(s) in the target table. The column is nullable, meaning it is not mandatory to provide an expression for tokenization. If a value is not provided, then the corresponding column(s) in the target table will not be tokenized.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'SelectExp'
GO
EXEC sp_addextendedproperty N'MS_Description', 'The column [flw].[IngestionTokenExp].[SelectExpFull] is a nullable NVARCHAR(2048) column in the table [flw].[IngestionTokenExp]. This column stores a full T-SQL SELECT statement expression used to generate the token values for the corresponding column specified in [flw].[IngestionTokenExp].[TokenExpAlias]. This expression can include multiple columns from the source table, and can utilize T-SQL functions or other expressions to calculate the token values. The expression is executed during the ingestion process, and the resulting token values are stored in a separate table while the original values are replaced with the generated tokens. If no expression is specified for a given [flw].[IngestionTokenExp].[TokenExpAlias], the original value will be stored without being tokenized.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'SelectExpFull'
GO
EXEC sp_addextendedproperty N'MS_Description', '[flw].[IngestionTokenExp].[TokenExpAlias] is a non-null column in the flw.IngestionTokenExp table that stores a unique alias that identifies how to tokenize data after the ingestion process has completed successfully. The alias is used to reference the specific tokenization expression in other parts of the data pipeline.', 'SCHEMA', N'flw', 'TABLE', N'IngestionTokenExp', 'COLUMN', N'TokenExpAlias'
GO
