SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [flw].[GetDefaultTrgDB] ()
RETURNS NVARCHAR(255)
AS
BEGIN

    RETURN (SELECT TOP 1 [DefaultTrgDbName] FROM [flw].[SysDefaultInitPipelineValues])
END;
GO
